# Generated by Django 3.2.25 on 2026-08-09 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('create_date',)},
        ),
    ]
