# Generated by Django 3.2.25 on 2026-09-03 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='github',
            new_name='instagram',
        ),
    ]
