# Generated by Django 3.2.25 on 2026-09-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_github_profile_instagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_preset',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
